### PR TITLE
Feat/74-json-schemas

### LINKED ISSUE #74: Add JSON schema to viewpoint, config, and command JSON
## Checklist before submitting a feature request

- [x] I have reviewed [CONTRIBUTING.md](https://github.com/opencaesar/oml-vision/blob/master/CONTRIBUTING.md) document
- [x] I have done a quick search on the issue tracker to check if the feature request is not redundant

## Is your feature request related to a problem? If yes, describe the problem

I am annoyed that there is no JSON schema to validate the viewpoint, config, and command JSONs.

## Describe the desired feature

Create a JSON schema to validate the viewpoint, config, and command JSONs.

## Additional context

JSON Schema:
https://json-schema.org

JSON Schema Contribution Point for VSCode Extension:
https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation

JSON to JSON Schema:
https://www.jsonschema.net

AJV:
https://ajv.js.org

### PR DESCRIPTION
**Pull request by pogi7**
## Checklist before submitting a merge request

- [x] I have reviewed [CONTRIBUTING.md](https://github.com/opencaesar/oml-vision/blob/master/CONTRIBUTING.md) document
- [x] All commits have been signed-off for the Developer Certificate of Origin. See [here](https://github.com/opencaesar/oml-vision/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).
- [x] I have added my contribution to [CHANGELOG.md](https://github.com/opencaesar/oml-vision/blob/master/CHANGELOG.md)
- [x] I have documented my code in the [OML Vision Docs](http://www.opencaesar.io/oml-vision-docs/)

## Description of contribution

closes #74 

## Testing performed

- [ ] I have added unit tests to cover additional functionality

## How to Test Expected functionality changes

[Describe expected behaviour changes in steps]

1. Open this repo in OML Vision https://github.com/UTNAK/kepler16b-using-imce-vocabulary
2. Click on the eye icon to activate OML Vision
3. Go into `src/vision/commands/compositions.json`
4. Remove line 6
5. Save the file
6. You should see a popup or in the console saying `Invalid or missing compositions.json.`
7. Undo deleting line 6
8. Save the file
9. You should see a popup or in the console saying `compositions.json loaded successfully.`
10. Go into `src/vision/config/sparqlConfig.json`
11. Remove lines 2-5
12. Save the file
13. You should see a popup or in the console saying `Invalid or missing sparqlConfig.json.`
14. Undo deleting lines 2-5
15. Save the file
16. You should see a popup or in the console saying `sparqlConfig.json loaded successfully.`
17. Go into `src/vision/viewpoints/pages.json`
18. Remove line 3
19. Save the file
20. You should see a popup or in the console saying `Invalid or missing pages.json.`
21. Undo deleting line 3
22. Save the file
23. You should see a popup or in the console saying `pages.json loaded successfully.`

## Additional context

#83 will add to this feature

### CODE REVIEW

**Review by aematei — CHANGES_REQUESTED** [review]
Everything works fine until `pages.json`. This is what I see when I both remove and restore line 3:
Screenshot 2024-06-10 at 12 08 31 PM

**Comment by aematei** [comment]
Okay I was poking around and noticed that the pages menu indeed indicates that there are no available pages to build:
image

**Comment by pogi7** [comment]
> Everything works fine until `pages.json`. This is what I see when I both remove and restore line 3: Screenshot 2024-06-10 at 12 08 31 PM

@aematei VSCode only shows 3 notifications by default.  The `pages.json` notification is not showing up.  You can check the console log to verify the error.

**Comment by aematei** [comment]
@pogi7 I checked the log and can confirm that the error is registered. I'll finish up the review.

**Review by aematei — APPROVED** [review]

**Pull request merged**
